// <auto-generated />
using System;
using BuildingFex.Api.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuildingFex.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610000000_IamInitial")]
    partial class IamInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BuildingFex.Api.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("AdmissionDate")
                        .HasColumnType("date")
                        .HasColumnName("admission_date");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("company");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Dni")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id");

                    b.Property<string>("Floor")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("floor");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<int?>("OwnerAdminId")
                        .HasColumnType("int")
                        .HasColumnName("owner_admin_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Ruc")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ruc");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_external_id");

                    b.HasIndex("OwnerAdminId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("BuildingFex.Api.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.HasOne("BuildingFex.Api.Iam.Domain.Model.Aggregates.User", "OwnerAdmin")
                        .WithMany()
                        .HasForeignKey("OwnerAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_users_users_owner_admin_id");

                    b.Navigation("OwnerAdmin");
                });
#pragma warning restore 612, 618
        }
    }
}
