// <auto-generated />
using System;
using BuildingFex.Api.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuildingFex.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615012133_AddSupportChats")]
    partial class AddSupportChats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BuildingFex.Api.Finances.Domain.Model.Aggregates.AdminManagementExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id");

                    b.Property<string>("InvoicePhotoUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("invoice_photo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("OwnerAdminId")
                        .HasColumnType("int")
                        .HasColumnName("owner_admin_id");

                    b.Property<string>("PurchaseDate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("purchase_date");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_admin_management_expenses");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("i_x_admin_management_expenses_external_id");

                    b.HasIndex("OwnerAdminId")
                        .HasDatabaseName("i_x_admin_management_expenses_owner_admin_id");

                    b.ToTable("admin_management_expenses");
                });

            modelBuilder.Entity("BuildingFex.Api.Finances.Domain.Model.Aggregates.Fee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DueDate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("due_date");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("month");

                    b.Property<int>("OwnerAdminId")
                        .HasColumnType("int")
                        .HasColumnName("owner_admin_id");

                    b.Property<string>("ResidentExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("resident_external_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_fees");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("i_x_fees_external_id");

                    b.HasIndex("OwnerAdminId")
                        .HasDatabaseName("i_x_fees_owner_admin_id");

                    b.ToTable("fees");
                });

            modelBuilder.Entity("BuildingFex.Api.Finances.Domain.Model.Aggregates.FinanceSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseMonthlyExpense")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_monthly_expense");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id");

                    b.Property<decimal>("LateFeeRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("late_fee_rate");

                    b.Property<int>("OwnerAdminId")
                        .HasColumnType("int")
                        .HasColumnName("owner_admin_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_finance_settings");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("i_x_finance_settings_external_id");

                    b.HasIndex("OwnerAdminId")
                        .HasDatabaseName("i_x_finance_settings_owner_admin_id");

                    b.ToTable("finance_settings");
                });

            modelBuilder.Entity("BuildingFex.Api.Finances.Domain.Model.Aggregates.FixedPayoutRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedAtIso")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("created_at_iso");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("dni");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("int")
                        .HasColumnName("interval_days");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("NextPaymentDate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("next_payment_date");

                    b.Property<int>("OwnerAdminId")
                        .HasColumnType("int")
                        .HasColumnName("owner_admin_id");

                    b.Property<string>("PaymentHistoryJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payment_history_json");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("phone");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("photo_url");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salary");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_fixed_payout_recipients");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("i_x_fixed_payout_recipients_external_id");

                    b.HasIndex("OwnerAdminId")
                        .HasDatabaseName("i_x_fixed_payout_recipients_owner_admin_id");

                    b.ToTable("fixed_payout_recipients");
                });

            modelBuilder.Entity("BuildingFex.Api.Finances.Domain.Model.Aggregates.KpiRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("EmptyUnits")
                        .HasColumnType("int")
                        .HasColumnName("empty_units");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id");

                    b.Property<int>("OccupiedUnits")
                        .HasColumnType("int")
                        .HasColumnName("occupied_units");

                    b.Property<int>("OwnerAdminId")
                        .HasColumnType("int")
                        .HasColumnName("owner_admin_id");

                    b.Property<decimal>("TotalDebt")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_debt");

                    b.Property<int>("TotalResidents")
                        .HasColumnType("int")
                        .HasColumnName("total_residents");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_kpi_records");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("i_x_kpi_records_external_id");

                    b.HasIndex("OwnerAdminId")
                        .HasDatabaseName("i_x_kpi_records_owner_admin_id");

                    b.ToTable("kpi_records");
                });

            modelBuilder.Entity("BuildingFex.Api.Finances.Domain.Model.Aggregates.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id");

                    b.Property<string>("FeeExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("fee_external_id");

                    b.Property<string>("FeeMonth")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("fee_month");

                    b.Property<string>("Method")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("method");

                    b.Property<int>("OwnerAdminId")
                        .HasColumnType("int")
                        .HasColumnName("owner_admin_id");

                    b.Property<string>("PaidAt")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("paid_at");

                    b.Property<string>("Reference")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("reference");

                    b.Property<string>("ResidentExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("resident_external_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_payments");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("i_x_payments_external_id");

                    b.HasIndex("OwnerAdminId")
                        .HasDatabaseName("i_x_payments_owner_admin_id");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("BuildingFex.Api.Finances.Domain.Model.Aggregates.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Concept")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("concept");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DueDate")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("due_date");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id");

                    b.Property<decimal>("ExtraCharges")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("extra_charges");

                    b.Property<string>("IssueDate")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("issue_date");

                    b.Property<decimal>("LateFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("late_fee");

                    b.Property<int>("OwnerAdminId")
                        .HasColumnType("int")
                        .HasColumnName("owner_admin_id");

                    b.Property<string>("ResidentExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("resident_external_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_receipts");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("i_x_receipts_external_id");

                    b.HasIndex("OwnerAdminId")
                        .HasDatabaseName("i_x_receipts_owner_admin_id");

                    b.ToTable("receipts");
                });

            modelBuilder.Entity("BuildingFex.Api.Finances.Domain.Model.Aggregates.SharedUtilityService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id");

                    b.Property<string>("Month")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("month");

                    b.Property<int>("OwnerAdminId")
                        .HasColumnType("int")
                        .HasColumnName("owner_admin_id");

                    b.Property<decimal?>("PerResidentShare")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("per_resident_share");

                    b.Property<int?>("ResidentCount")
                        .HasColumnType("int")
                        .HasColumnName("resident_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_shared_utility_services");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("i_x_shared_utility_services_external_id");

                    b.HasIndex("OwnerAdminId")
                        .HasDatabaseName("i_x_shared_utility_services_owner_admin_id");

                    b.ToTable("shared_utility_services");
                });

            modelBuilder.Entity("BuildingFex.Api.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<DateTime?>("AdmissionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("admission_date");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("company");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Dni")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id");

                    b.Property<string>("Floor")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("floor");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<int?>("OwnerAdminId")
                        .HasColumnType("int")
                        .HasColumnName("owner_admin_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Ruc")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ruc");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_external_id");

                    b.HasIndex("OwnerAdminId")
                        .HasDatabaseName("i_x_users_owner_admin_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("BuildingFex.Api.Incidents.Domain.Model.Aggregates.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id");

                    b.Property<int>("OwnerAdminId")
                        .HasColumnType("int")
                        .HasColumnName("owner_admin_id");

                    b.Property<string>("Provider")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("reported_at");

                    b.Property<string>("ResidentExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("resident_external_id");

                    b.Property<string>("ResidentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("resident_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_incidents");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("i_x_incidents_external_id");

                    b.HasIndex("OwnerAdminId")
                        .HasDatabaseName("i_x_incidents_owner_admin_id");

                    b.ToTable("incidents");
                });

            modelBuilder.Entity("BuildingFex.Api.Information.Domain.Model.Aggregates.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("author_name");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id");

                    b.Property<int>("OwnerAdminId")
                        .HasColumnType("int")
                        .HasColumnName("owner_admin_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("priority");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_announcements");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("i_x_announcements_external_id");

                    b.HasIndex("OwnerAdminId")
                        .HasDatabaseName("i_x_announcements_owner_admin_id");

                    b.ToTable("announcements");
                });

            modelBuilder.Entity("BuildingFex.Api.SocialSpaces.Domain.Model.Aggregates.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("date");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("end_time");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id");

                    b.Property<string>("GuestInviteToken")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("guest_invite_token");

                    b.Property<string>("GuestsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("guests_json");

                    b.Property<int>("OwnerAdminId")
                        .HasColumnType("int")
                        .HasColumnName("owner_admin_id");

                    b.Property<string>("ResidentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("resident_code");

                    b.Property<string>("ResidentExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("resident_external_id");

                    b.Property<string>("ResidentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("resident_name");

                    b.Property<string>("SpaceExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("space_external_id");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("start_time");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_reservations");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("i_x_reservations_external_id");

                    b.HasIndex("GuestInviteToken")
                        .HasDatabaseName("i_x_reservations_guest_invite_token");

                    b.HasIndex("OwnerAdminId")
                        .HasDatabaseName("i_x_reservations_owner_admin_id");

                    b.ToTable("reservations");
                });

            modelBuilder.Entity("BuildingFex.Api.SocialSpaces.Domain.Model.Aggregates.SocialSpace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("OwnerAdminId")
                        .HasColumnType("int")
                        .HasColumnName("owner_admin_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_social_spaces");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("i_x_social_spaces_external_id");

                    b.HasIndex("OwnerAdminId")
                        .HasDatabaseName("i_x_social_spaces_owner_admin_id");

                    b.ToTable("social_spaces");
                });

            modelBuilder.Entity("BuildingFex.Api.Support.Domain.Model.Aggregates.SupportChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("external_id");

                    b.Property<string>("MessagesJson")
                        .IsRequired()
                        .HasColumnType("LONGTEXT")
                        .HasColumnName("messages_json");

                    b.Property<string>("OwnerAdminId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("owner_admin_id");

                    b.Property<string>("ResidentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("resident_id");

                    b.Property<string>("ResidentName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("resident_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("topic");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_support_chats");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("i_x_support_chats_external_id");

                    b.ToTable("support_chats");
                });

            modelBuilder.Entity("BuildingFex.Api.Finances.Domain.Model.Aggregates.AdminManagementExpense", b =>
                {
                    b.HasOne("BuildingFex.Api.Iam.Domain.Model.Aggregates.User", "OwnerAdmin")
                        .WithMany()
                        .HasForeignKey("OwnerAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_admin_management_expenses__user_owner_admin_id");

                    b.Navigation("OwnerAdmin");
                });

            modelBuilder.Entity("BuildingFex.Api.Finances.Domain.Model.Aggregates.Fee", b =>
                {
                    b.HasOne("BuildingFex.Api.Iam.Domain.Model.Aggregates.User", "OwnerAdmin")
                        .WithMany()
                        .HasForeignKey("OwnerAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_fees__user_owner_admin_id");

                    b.Navigation("OwnerAdmin");
                });

            modelBuilder.Entity("BuildingFex.Api.Finances.Domain.Model.Aggregates.FinanceSetting", b =>
                {
                    b.HasOne("BuildingFex.Api.Iam.Domain.Model.Aggregates.User", "OwnerAdmin")
                        .WithMany()
                        .HasForeignKey("OwnerAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_finance_settings__user_owner_admin_id");

                    b.Navigation("OwnerAdmin");
                });

            modelBuilder.Entity("BuildingFex.Api.Finances.Domain.Model.Aggregates.FixedPayoutRecipient", b =>
                {
                    b.HasOne("BuildingFex.Api.Iam.Domain.Model.Aggregates.User", "OwnerAdmin")
                        .WithMany()
                        .HasForeignKey("OwnerAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_fixed_payout_recipients__user_owner_admin_id");

                    b.Navigation("OwnerAdmin");
                });

            modelBuilder.Entity("BuildingFex.Api.Finances.Domain.Model.Aggregates.KpiRecord", b =>
                {
                    b.HasOne("BuildingFex.Api.Iam.Domain.Model.Aggregates.User", "OwnerAdmin")
                        .WithMany()
                        .HasForeignKey("OwnerAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_kpi_records__user_owner_admin_id");

                    b.Navigation("OwnerAdmin");
                });

            modelBuilder.Entity("BuildingFex.Api.Finances.Domain.Model.Aggregates.Payment", b =>
                {
                    b.HasOne("BuildingFex.Api.Iam.Domain.Model.Aggregates.User", "OwnerAdmin")
                        .WithMany()
                        .HasForeignKey("OwnerAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_payments__user_owner_admin_id");

                    b.Navigation("OwnerAdmin");
                });

            modelBuilder.Entity("BuildingFex.Api.Finances.Domain.Model.Aggregates.Receipt", b =>
                {
                    b.HasOne("BuildingFex.Api.Iam.Domain.Model.Aggregates.User", "OwnerAdmin")
                        .WithMany()
                        .HasForeignKey("OwnerAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_receipts__user_owner_admin_id");

                    b.Navigation("OwnerAdmin");
                });

            modelBuilder.Entity("BuildingFex.Api.Finances.Domain.Model.Aggregates.SharedUtilityService", b =>
                {
                    b.HasOne("BuildingFex.Api.Iam.Domain.Model.Aggregates.User", "OwnerAdmin")
                        .WithMany()
                        .HasForeignKey("OwnerAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_shared_utility_services__user_owner_admin_id");

                    b.Navigation("OwnerAdmin");
                });

            modelBuilder.Entity("BuildingFex.Api.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.HasOne("BuildingFex.Api.Iam.Domain.Model.Aggregates.User", "OwnerAdmin")
                        .WithMany()
                        .HasForeignKey("OwnerAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_users_users_owner_admin_id");

                    b.Navigation("OwnerAdmin");
                });

            modelBuilder.Entity("BuildingFex.Api.Incidents.Domain.Model.Aggregates.Incident", b =>
                {
                    b.HasOne("BuildingFex.Api.Iam.Domain.Model.Aggregates.User", "OwnerAdmin")
                        .WithMany()
                        .HasForeignKey("OwnerAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_incidents_users_owner_admin_id");

                    b.Navigation("OwnerAdmin");
                });

            modelBuilder.Entity("BuildingFex.Api.Information.Domain.Model.Aggregates.Announcement", b =>
                {
                    b.HasOne("BuildingFex.Api.Iam.Domain.Model.Aggregates.User", "OwnerAdmin")
                        .WithMany()
                        .HasForeignKey("OwnerAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_announcements_users_owner_admin_id");

                    b.Navigation("OwnerAdmin");
                });

            modelBuilder.Entity("BuildingFex.Api.SocialSpaces.Domain.Model.Aggregates.Reservation", b =>
                {
                    b.HasOne("BuildingFex.Api.Iam.Domain.Model.Aggregates.User", "OwnerAdmin")
                        .WithMany()
                        .HasForeignKey("OwnerAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_reservations_users_owner_admin_id");

                    b.Navigation("OwnerAdmin");
                });

            modelBuilder.Entity("BuildingFex.Api.SocialSpaces.Domain.Model.Aggregates.SocialSpace", b =>
                {
                    b.HasOne("BuildingFex.Api.Iam.Domain.Model.Aggregates.User", "OwnerAdmin")
                        .WithMany()
                        .HasForeignKey("OwnerAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_social_spaces_users_owner_admin_id");

                    b.Navigation("OwnerAdmin");
                });
#pragma warning restore 612, 618
        }
    }
}
