namespace BuildingFex.Api.Finances.Application.Internal.MercadoPago;

public interface IMercadoPagoService
{
    /// <summary>
    /// Creates a Mercado Pago Checkout Pro preference for the given receipt.
    /// </summary>
    Task<PreferenceResult> CreatePreferenceAsync(CreatePreferenceRequest request, CancellationToken ct = default);

    /// <summary>
    /// Processes a card payment using the token generated by Mercado Pago Bricks.
    /// </summary>
    Task<CardPaymentResult> ProcessCardPaymentAsync(CardPaymentRequest request, CancellationToken ct = default);

    /// <summary>
    /// Handles a Mercado Pago webhook/IPN notification and reconciles payment status.
    /// </summary>
    Task<WebhookResult> HandleWebhookAsync(long mpPaymentId, CancellationToken ct = default);
}
